ARG GO_VERSION=1.18.1-alpine3.15
FROM golang:${GO_VERSION}
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
WORKDIR /build
COPY ./src/ .
COPY ./src/go.mod .
COPY ./src/go.sum .
RUN go mod download && \
    go build -o main .
WORKDIR /dist
RUN cp /build/.env .env
RUN cp -R /build/files files/
RUN cp /build/main .
EXPOSE 8080
CMD ["/dist/main"]